services:
  db:
    image: postgres:17.6-alpine
    container_name: payment-api-database
    restart: always
    env_file:
      - ./docker-compose-env/database.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - soat-payment

  test_db:
    image: postgres:17.6-alpine
    container_name: payment-api-test-database
    restart: always
    env_file:
      - ./docker-compose-env/test_database.env
    ports:
      - ${POSTGRES_TEST_PORT:-5433}:5432
    expose:
      - "5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    networks:
      - soat-payment

  api:
    container_name: payment-api
    image: payment-api:dev
    restart: always
    expose:
      - 8000
    build:
      context: .
      target: development
    ports:
      - ${PAYMENT_API_HTTP_PORT:-8000}:8000
    entrypoint: ["sh", "/app/docker-entrypoint/start_dev_api.sh"]
    volumes:
      - ./payment_api:/app/payment_api
      - ./tests:/app/tests
      - ./docker-entrypoint:/app/docker-entrypoint
      - ./alembic.ini:/app/alembic.ini
      - ./logging.ini:/app/logging.ini
      - ./pytest.ini:/app/pytest.ini
      - ./.coveragerc:/app/.coveragerc
      - ./settings:/app/settings
    depends_on:
      - db
    env_file:
      - ./docker-compose-env/app.env
    networks:
      - soat-payment
  order-created-listener:
    container_name: order-created-listener
    image: payment-api:dev
    restart: always
    entrypoint: ["sh", "/app/docker-entrypoint/start_order_created_listener.sh"]
    volumes:
      - ./payment_api:/app/payment_api
      - ./docker-entrypoint:/app/docker-entrypoint
      - ./logging.ini:/app/logging.ini
      - ./settings:/app/settings
    depends_on:
      - db
    networks:
      - soat-payment

volumes:
  db-data:
  db-dev-data:

networks:
  soat-payment:
    driver: bridge
