name: CI / CD Pipeline
on:
  - push
  - workflow_dispatch

env:
  APP_IMAGE: "public.ecr.aws/p6c0d2v5/fiap-soat-techchallenge-payment:latest"

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build application for testing
        run: docker compose -f docker-compose.test.yml build --no-cache api

      - name: Pull test database image
        run: docker compose -f docker-compose.test.yml pull test_db

      - name: Create DB env file
        run: |
          cat << EOF > docker-compose-env/test_database.env
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=12345
          POSTGRES_DB=postgres
          EOF

      - name: Create API env file
        run: touch docker-compose-env/app.env

      - name: Create the testing database configuration file for the application
        run: |
          cat << EOF > settings/test_database.env
          DSN="postgresql+asyncpg://postgres:12345@test_db:5432/postgres"
          ECHO=True
          EOF

      - name: Start test services
        run: docker compose -f docker-compose.test.yml up -d

      - name: Run tests
        run: docker compose -f docker-compose.test.yml exec api pytest

      - name: Copy coverage report
        run: docker cp payment-api:/app/coverage.xml ./coverage.xml

      - name: Destroy test services
        run: docker compose -f docker-compose.test.yml down -v

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

  sonarqube:
    name: SonarQube
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'SOAT-Tech-Challenge-2025/payment-api'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@40f5b61913e891f9d316696628698051136015be
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@95b1cc6c02a15c8ecc00c07b1c2a75ed61a14055
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_and_push:
    name: Build and Push Docker Image
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_ACCESS_SECRET }}
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.APP_IMAGE }}
          target: production

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/main' && github.repository == 'SOAT-Tech-Challenge-2025/payment-api'
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}

      - name: Create backend.hcl configuration file
        run: |
          cat << EOF > backend.hcl
          bucket         = "${{ vars.TF_BACKEND_BUCKET }}"
          key            = "${{ vars.TF_BACKEND_KEY }}"
          region         = "${{ vars.AWS_REGION }}"
          dynamodb_table = "${{ vars.TF_BACKEND_DYNAMO_TABLE }}"
          encrypt        = true
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var region="${{ vars.AWS_REGION }}" \
            -var docker_api_image="${{ env.APP_IMAGE }}" \
            -var force_rollout="$(date +%s)" \
            -var aws_account_id="${{ secrets.AWS_ACCOUNT_ID }}" \
            -var aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var database_address="${{ secrets.DATABASE_ADDRESS }}" \
            -var database_name="${{ secrets.DATABASE_NAME }}" \
            -var database_port="${{ secrets.DATABASE_PORT }}" \
            -var database_user="${{ secrets.DATABASE_USER }}" \
            -var database_password="${{ secrets.DATABASE_PASSWORD }}" \
            -var mercado_pago_access_token="${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}" \
            -var mercado_pago_user_id="${{ secrets.MERCADO_PAGO_USER_ID }}" \
            -var mercado_pago_pos="${{ secrets.MERCADO_PAGO_POS }}" \
            -var mercado_pago_webhook_key="${{ secrets.MERCADO_PAGO_WEBHOOK_KEY }}" \
            -var order_created_listener_queue_name="${{ secrets.ORDER_CREATED_LISTENER_QUEUE_NAME }}" \
            -var payment_closed_publisher_topic_arn="${{ secrets.PAYMENT_CLOSED_PUBLISHER_TOPIC_ARN }}" \
            -var payment_closed_publisher_group_id="${{ secrets.PAYMENT_CLOSED_PUBLISHER_GROUP_ID }}"
